// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZm8o2UBjanvnpE9_P1ryb0mUImlxa8o',
    appId: '1:147713194154:android:64268d51c4ffe78f0af8d3',
    messagingSenderId: '147713194154',
    projectId: 'fir-fa0cb',
    storageBucket: 'fir-fa0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu-z26AJbVG-Fj7DVE-hPATd_IUI0VhlU',
    appId: '1:147713194154:ios:8f840aceaa49af9b0af8d3',
    messagingSenderId: '147713194154',
    projectId: 'fir-fa0cb',
    storageBucket: 'fir-fa0cb.firebasestorage.app',
    androidClientId: '147713194154-96u4lli0lu0sriqvi4q1v9n4cl49n4qq.apps.googleusercontent.com',
    iosClientId: '147713194154-ej2o1hghciier9thte7ll3k5q0itj407.apps.googleusercontent.com',
    iosBundleId: 'com.example.halofund',
  );

}